function [scenario, egoVehicle] = Oval_clockwise()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 04-Oct-2023 15:36:42

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 -50 0;
    40 -50 0;
    49 -50 0.45;
    50 -50 0.45;
    100 0 0.45;
    50 50 0.45;
    49 50 0.45;
    40 50 0;
    -40 50 0;
    -49 50 0.45;
    -50 50 0.45;
    -100 0 0.45;
    -50 -50 0.45;
    -49 -50 0.45;
    -40 -50 0;
    0 -50 0];

laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [3.5 48.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [3.5 48.1 0;
    40.9 48 0;
    64.7 46.2 0.2;
    82.5 36.1 0.3;
    94.1 19.3 0.2;
    98 5.6 0.2;
    96.2 -15.9 0.3;
    91.6 -24.6 0.2;
    80.3 -37.7 0.2;
    67.3 -45.4 0.3;
    53.2 -48.4 0.2;
    19.2 -48 0;
    -29.2 -48.1 0;
    -52.3 -48 0.2;
    -61.3 -46.6 0.2;
    -73.7 -42 0.2;
    -86.4 -31.8 0.2;
    -94.7 -17.7 0.2;
    -97.7 -0.1 0.1;
    -97.1 10.3 0.2;
    -91.1 26.3 0.3;
    -76.3 40.5 0.2;
    -63.12 46.57 0.23;
    -54.29 48.34 0.25;
    -35.52 48.03 0.01;
    -5.9 48.03 0.01;
    6.6 48 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
jerk = 0.1;
smoothTrajectory(egoVehicle, waypoints, speed, 'Jerk', jerk);

% Add the non-ego actors
fastCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [82.5935654028723 -494.956102047486 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'fastCar');
waypoints = [82.5935654028723 -494.956102047486 0;
    109.734171567359 -489.654624802447 0;
    136.541518659389 -482.866082555182 0;
    162.93419364691 -474.611091885378 0;
    188.832042843424 -464.914722928388 0;
    214.156415332095 -453.806423238044 0;
    238.830401826004 -441.319928355416 0;
    262.779068239117 -427.493159355073 0;
    285.929683258652 -412.368107680028 0;
    308.211939227675 -395.99070761511 0;
    329.558165667153 -378.410696786047 0;
    349.903534788967 -359.681465107929 0;
    369.186258375777 -339.859892641797 0;
    387.34777542981 -319.006176851762 0;
    404.332930020679 -297.183649787287 0;
    420.090138792137 -274.458585745834 0;
    434.571547619031 -250.9 0];
speed = 19.4;
trajectory(fastCar, waypoints, speed);

