function [scenario, egoVehicle] = Oval_counterclockwise()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 04-Oct-2023 16:03:18

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 -50 0;
    40 -50 0;
    49 -50 0.45;
    50 -50 0.45;
    100 0 0.45;
    50 50 0.45;
    49 50 0.45;
    40 50 0;
    -40 50 0;
    -49 50 0.45;
    -50 50 0.45;
    -100 0 0.45;
    -50 -50 0.45;
    -49 -50 0.45;
    -40 -50 0;
    0 -50 0];

laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [2.6 48.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [2.6 48.1 0;
    -24.3 48.1 0;
    -49.2 48 0.2;
    -60.5 47.3 0.2;
    -72.4 42.9 0.2;
    -84.3 33.7 0.2;
    -95.1 17.7 0.2;
    -98.6 0.2 0.3;
    -94.9 -18.5 0.3;
    -85.9 -32.6 0.3;
    -71.2 -43.6 0.2;
    -54.2 -48.3 0.2;
    -23.2 -48.1 0;
    17.2 -48.2 0;
    48.7 -48.2 0.2;
    61.7 -47.2 0.3;
    74.4 -41.6 0.2;
    85.5 -33 0.2;
    94 -20.1 0.2;
    97.6 -8.1 0.2;
    98.4 6.4 0.3;
    94.4 19.2 0.2;
    85.9 32.8 0.3;
    70.7 43.5 0.2;
    53.1 48.6 0.3;
    26.7 48.1 0;
    3.5 48.3 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
jerk = 0.1;
smoothTrajectory(egoVehicle, waypoints, speed, 'Jerk', jerk);

% Add the non-ego actors
fastCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [82.5935654028723 -494.956102047486 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'fastCar');
waypoints = [82.5935654028723 -494.956102047486 0;
    109.734171567359 -489.654624802447 0;
    136.541518659389 -482.866082555182 0;
    162.93419364691 -474.611091885378 0;
    188.832042843424 -464.914722928388 0;
    214.156415332095 -453.806423238044 0;
    238.830401826004 -441.319928355416 0;
    262.779068239117 -427.493159355073 0;
    285.929683258652 -412.368107680028 0;
    308.211939227675 -395.99070761511 0;
    329.558165667153 -378.410696786047 0;
    349.903534788967 -359.681465107929 0;
    369.186258375777 -339.859892641797 0;
    387.34777542981 -319.006176851762 0;
    404.332930020679 -297.183649787287 0;
    420.090138792137 -274.458585745834 0;
    434.571547619031 -250.9 0];
speed = 19.4;
trajectory(fastCar, waypoints, speed);

